name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and publish
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: '18'

      - name: install dependencies
        run: |
          npm install --force

      - name: build
        run: |
          npm run build

      - name: deploy
        run: |
          GIT_USER=guiyomh npm run deploy
